'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Image from 'next/image'
import Link from 'next/link'
import {
  CheckCircle2,
  ChevronRight,
  MapPin,
  Package,
  Truck,
  X,
  CreditCard,
  QrCode,
} from 'lucide-react'
import { useCart } from '@/providers/cart'
import { sdk } from '@/lib/sdk'
import { formatPrice } from '@/lib/format'
import { getMedusaTokenFromCookie, syncMedusaTokenFromClient } from '@/lib/medusa-client-sync'
import { Divider } from '@/components/atoms'
import type { HttpTypes } from '@medusajs/types'

type ShippingOption = {
  id: string
  name: string
  amount: number | null
  fulfillmentSetType: string  // 'shipping' | 'pickup' from service_zone.fulfillment_set.type
}

type PaymentMethod = 'deuna' | 'transfer' | 'card' | null

interface BillingAddress {
  first_name: string
  last_name: string
  address_1: string
  city: string
  province: string
  postal_code: string
  phone: string
}

// ─── Payment modal ─────────────────────────────────────────────────────────────
function PaymentModal({
  method,
  onClose,
  onTransferConfirm,
  isLoading,
  error,
  currencyCode,
}: {
  method: PaymentMethod
  onClose: () => void
  onTransferConfirm: () => void
  isLoading: boolean
  error: string
  currencyCode: string
}) {
  if (!method) return null

  const titles: Record<NonNullable<PaymentMethod>, string> = {
    deuna: 'Pagar con DeUna',
    transfer: 'Transferencia bancaria',
    card: 'Tarjeta de débito / crédito',
  }

  return (
    <>
      <div className="fixed inset-0 bg-black/50 z-40" onClick={onClose} />
      <div className="fixed inset-x-0 bottom-0 md:inset-0 md:flex md:items-center md:justify-center z-50 p-0 md:p-4">
        <div className="bg-bg-surface rounded-t-2xl md:rounded-2xl w-full md:max-w-[440px] flex flex-col max-h-[90vh]">

          {/* Drag handle (mobile) */}
          <div className="flex justify-center pt-3 pb-1 md:hidden">
            <div className="w-10 h-1 rounded-full bg-bg-elevated" />
          </div>

          {/* Header */}
          <div className="flex items-center justify-between px-5 py-4 border-b border-border">
            <span className="font-heading text-lg font-bold text-text-primary">{titles[method]}</span>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg bg-bg-elevated flex items-center justify-center"
            >
              <X className="w-4 h-4 text-text-primary" />
            </button>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto px-5 py-6 flex flex-col items-center gap-5">

            {/* ── DeUna ── */}
            {method === 'deuna' && (
              <>
                <p className="text-sm text-text-secondary text-center">
                  Escanea el código QR con la app de DeUna para completar tu pago.
                </p>
                {/* QR placeholder — replace with real QR generated by DeUna payment session */}
                <div className="w-52 h-52 rounded-2xl bg-bg-elevated border-2 border-dashed border-border-accent flex flex-col items-center justify-center gap-3">
                  <QrCode className="w-14 h-14 text-text-muted" />
                  <span className="text-xs text-text-muted text-center px-4 leading-5">
                    QR de pago DeUna<br />aparecerá aquí
                  </span>
                </div>
                <p className="text-xs text-text-muted text-center leading-5">
                  Una vez completado el pago en la app, tu pedido se confirmará automáticamente.
                </p>
              </>
            )}

            {/* ── Transfer ── */}
            {method === 'transfer' && (
              <>
                <p className="text-sm text-text-secondary text-center">
                  Realiza la transferencia a la cuenta indicada y envíanos el comprobante por WhatsApp.
                </p>
                {/* Bank details — TODO: Replace with real bank account info */}
                <div className="w-full rounded-xl bg-bg-elevated border border-border p-4 flex flex-col gap-3 text-sm">
                  {[
                    { label: 'Banco', value: 'Banco Pichincha' },
                    { label: 'Tipo de cuenta', value: 'Corriente' },
                    { label: 'Número', value: 'XXXXXXXXXX' },
                    { label: 'Titular', value: 'Kādo Gallery' },
                    { label: 'RUC / CI', value: 'XXXXXXXXXX' },
                  ].map(({ label, value }) => (
                    <div key={label} className="flex justify-between items-center">
                      <span className="text-text-muted">{label}</span>
                      <span className="font-semibold text-text-primary">{value}</span>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-text-muted text-center leading-5">
                  Tu pedido quedará pendiente hasta confirmar el comprobante de pago.
                </p>
                {error && (
                  <p className="text-xs text-[var(--danger)] text-center">{error}</p>
                )}
                <button
                  onClick={onTransferConfirm}
                  disabled={isLoading}
                  className="w-full h-11 rounded-xl bg-accent-primary text-white font-bold text-sm disabled:opacity-60 transition-opacity"
                >
                  {isLoading ? 'Procesando...' : 'Confirmar pedido'}
                </button>
              </>
            )}

            {/* ── Card (placeholder) ── */}
            {method === 'card' && (
              <div className="w-full rounded-2xl bg-bg-elevated border-2 border-dashed border-border-accent flex flex-col items-center justify-center gap-3 py-12 px-6">
                <CreditCard className="w-12 h-12 text-text-muted" />
                <span className="font-heading text-lg font-semibold text-text-primary">Próximamente</span>
                <p className="text-sm text-text-muted text-center leading-6">
                  El pago con tarjeta estará disponible muy pronto.<br />
                  Por ahora usa <strong className="text-text-secondary">DeUna</strong> o <strong className="text-text-secondary">Transferencia</strong>.
                </p>
              </div>
            )}

          </div>
        </div>
      </div>
    </>
  )
}

// ─── Checkout page ─────────────────────────────────────────────────────────────
export default function CheckoutPage() {
  const router = useRouter()
  const { cart, unsetCart } = useCart()
  const items = cart?.items ?? []
  const currencyCode = cart?.currency_code ?? 'USD'
  const subtotal = cart?.subtotal ?? 0

  const [fulfillmentType, setFulfillmentType] = useState<'pickup' | 'delivery'>('delivery')
  const [addresses, setAddresses] = useState<HttpTypes.StoreCustomerAddress[]>([])
  const [selectedAddress, setSelectedAddress] = useState<HttpTypes.StoreCustomerAddress | null>(null)
  // null = fetch in progress, [] = no options, [...] = options loaded
  const [shippingOptions, setShippingOptions] = useState<ShippingOption[] | null>(null)
  const [selectedShippingId, setSelectedShippingId] = useState<string | null>(null)
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState('')
  const [billing, setBilling] = useState<BillingAddress>({
    first_name: '', last_name: '', address_1: '', city: '',
    province: '', postal_code: '', phone: '',
  })

  const cartId = cart?.id

  // Load customer saved addresses client-side
  useEffect(() => {
    async function loadAddresses() {
      let token = getMedusaTokenFromCookie()
      if (!token) {
        await syncMedusaTokenFromClient()
        token = getMedusaTokenFromCookie()
      }
      if (!token) return
      try {
        const { addresses: data } = await sdk.store.customer.listAddress(
          {},
          { Authorization: `Bearer ${token}` }
        )
        setAddresses(data ?? [])
        if (data?.length > 0) setSelectedAddress(data[0])
      } catch { /* guest checkout — no addresses */ }
    }
    loadAddresses()
  }, [])

  // Fetch ALL shipping options once (both delivery and pickup).
  // All setState calls are inside async callbacks to satisfy react-hooks/set-state-in-effect.
  useEffect(() => {
    if (!cartId) return
    sdk.store.fulfillment
      .listCartOptions({ cart_id: cartId })
      .then(({ shipping_options }) => {
        const raw = shipping_options as unknown as Array<{
          id: string
          name: string
          amount: number | null
          service_zone?: { fulfillment_set?: { type?: string } }
        }>
        const PICKUP_KEYWORDS = ['pickup', 'retiro', 'tienda', 'store']
        const isPickup = (o: { name: string; service_zone?: { fulfillment_set?: { type?: string } } }) =>
          o.service_zone?.fulfillment_set?.type === 'pickup' ||
          PICKUP_KEYWORDS.some((kw) => o.name.toLowerCase().includes(kw))
        const opts: ShippingOption[] = raw.map((o) => ({
          id: o.id,
          name: o.name,
          amount: o.amount,
          fulfillmentSetType: isPickup(o) ? 'pickup' : 'shipping',
        }))
        setShippingOptions(opts)
        const firstDelivery = opts.find((o) => o.fulfillmentSetType !== 'pickup')
        if (firstDelivery) setSelectedShippingId(firstDelivery.id)
      })
      .catch(() => setShippingOptions([]))
    return () => setShippingOptions(null)
  }, [cartId])

  const deliveryOptions = (shippingOptions ?? []).filter((o) => o.fulfillmentSetType !== 'pickup')
  const selectedShipping = deliveryOptions.find((o) => o.id === selectedShippingId)
  const shippingCost = fulfillmentType === 'delivery' ? (selectedShipping?.amount ?? 0) : 0
  const total = subtotal + shippingCost

  const handleTransferConfirm = async () => {
    if (!cart?.id) return
    setIsSubmitting(true)
    setSubmitError('')
    try {
      const token = getMedusaTokenFromCookie()
      const authHeaders: Record<string, string> = token ? { Authorization: `Bearer ${token}` } : {}

      // 1. Add shipping method
      if (fulfillmentType === 'delivery' && selectedShippingId) {
        await sdk.store.cart.addShippingMethod(cart.id, { option_id: selectedShippingId })
      } else if (fulfillmentType === 'pickup') {
        const pickupOption = shippingOptions?.find((o) => o.fulfillmentSetType === 'pickup')
        if (!pickupOption) throw new Error('No se encontró una opción de retiro en tienda.')
        await sdk.store.cart.addShippingMethod(cart.id, { option_id: pickupOption.id })
      }

      // 2. Link customer to cart
      if (token) {
        await sdk.store.cart.transferCart(cart.id, {}, authHeaders)
      }

      // 3. Set billing / shipping addresses
      const billingAddress = {
        first_name: billing.first_name || undefined,
        last_name: billing.last_name || undefined,
        address_1: billing.address_1 || undefined,
        city: billing.city || undefined,
        province: billing.province || undefined,
        postal_code: billing.postal_code || undefined,
        phone: billing.phone || undefined,
        country_code: 'ec',
      }
      const shippingAddress = selectedAddress
        ? {
            first_name: selectedAddress.first_name ?? undefined,
            last_name: selectedAddress.last_name ?? undefined,
            address_1: selectedAddress.address_1 ?? undefined,
            city: selectedAddress.city ?? undefined,
            province: selectedAddress.province ?? undefined,
            postal_code: selectedAddress.postal_code ?? undefined,
            phone: selectedAddress.phone ?? undefined,
            country_code: selectedAddress.country_code ?? 'ec',
          }
        : undefined
      const addressUpdate: HttpTypes.StoreUpdateCart = {
        ...(billingAddress && { billing_address: billingAddress }),
        ...(shippingAddress && { shipping_address: shippingAddress }),
      }
      if (Object.keys(addressUpdate).length > 0) {
        await sdk.store.cart.update(cart.id, addressUpdate)
      }

      // 4. Initiate payment session if none exists
      const { cart: freshCart } = await sdk.store.cart.retrieve(cart.id, {
        fields: '+payment_collection',
      })
      const hasSession = (freshCart.payment_collection?.payment_sessions?.length ?? 0) > 0
      if (!hasSession) {
        await sdk.store.payment.initiatePaymentSession(freshCart, {
          provider_id: 'pp_system_default',
        })
      }

      // 5. Complete cart → order
      const result = await sdk.store.cart.complete(cart.id, {}, authHeaders)
      const order = (result as { order?: HttpTypes.StoreOrder }).order
      if (order) {
        unsetCart()
        router.push(`/order-confirmation?id=${order.id}`)
      }
    } catch (err) {
      console.error('[checkout]', err)
      const msg = err instanceof Error ? err.message : ''
      setSubmitError(
        msg.includes('shipping profiles')
          ? 'Error de configuración de envío. Contacta al soporte.'
          : 'Ocurrió un error al procesar el pedido. Intenta de nuevo.'
      )
    } finally {
      setIsSubmitting(false)
    }
  }

  // Empty cart guard
  if (items.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center gap-4 py-24 px-4">
        <Package className="w-16 h-16 text-text-muted" />
        <h1 className="font-heading text-2xl font-bold text-text-primary">Tu carrito está vacío</h1>
        <Link
          href="/sealed"
          className="flex items-center justify-center h-11 px-6 rounded-xl bg-accent-primary text-sm font-bold text-white"
        >
          Ver catálogo
        </Link>
      </div>
    )
  }

  return (
    <>
      <div className="max-w-[1280px] mx-auto px-4 py-6 flex flex-col gap-6">

        {/* Breadcrumb */}
        <div className="flex items-center gap-2">
          <Link href="/cart" className="text-sm text-text-muted hover:text-text-primary transition-colors">
            Carrito
          </Link>
          <ChevronRight className="w-3 h-3 text-text-muted" />
          <span className="text-sm font-semibold text-text-primary">Checkout</span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-5">

          {/* ── Left column ───────────────────────────────────── */}
          <div className="flex flex-col gap-4">

            {/* Products */}
            <div className="bg-bg-surface rounded-2xl border border-border p-5 flex flex-col gap-1">
              <h2 className="font-heading text-base font-bold text-text-primary mb-3">
                Productos ({items.length})
              </h2>
              {items.map((item, idx) => {
                const imageUrl = item.variant?.product?.thumbnail ?? item.thumbnail ?? undefined
                return (
                  <div key={item.id}>
                    {idx > 0 && <Divider className="my-3" />}
                    <div className="flex items-center gap-3">
                      <div className="w-14 h-14 rounded-lg bg-bg-elevated flex-shrink-0 relative overflow-hidden">
                        {imageUrl && (
                          <Image src={imageUrl} alt={item.title ?? ''} fill className="object-cover" sizes="56px" />
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-[13px] font-semibold text-text-primary line-clamp-1">{item.title}</p>
                        <p className="text-xs text-text-muted mt-0.5">
                          {item.variant_title} · x{item.quantity}
                        </p>
                      </div>
                      <span className="font-heading text-base font-bold text-accent-primary shrink-0">
                        {formatPrice((item.unit_price ?? 0) * (item.quantity ?? 1), currencyCode)}
                      </span>
                    </div>
                  </div>
                )
              })}
            </div>

            {/* Fulfillment type */}
            <div className="bg-bg-surface rounded-2xl border border-border p-5 flex flex-col gap-4">
              <h2 className="font-heading text-base font-bold text-text-primary">Entrega</h2>

              <div className="grid grid-cols-2 gap-3">
                {(['delivery', 'pickup'] as const).map((type) => (
                  <button
                    key={type}
                    onClick={() => setFulfillmentType(type)}
                    className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-colors ${
                      fulfillmentType === type
                        ? 'border-accent-primary bg-(--accent-primary)/5'
                        : 'border-border hover:border-border-accent'
                    }`}
                  >
                    {type === 'delivery' ? (
                      <Truck className={`w-5 h-5 ${fulfillmentType === type ? 'text-accent-primary' : 'text-text-muted'}`} />
                    ) : (
                      <Package className={`w-5 h-5 ${fulfillmentType === type ? 'text-accent-primary' : 'text-text-muted'}`} />
                    )}
                    <span className={`text-sm font-semibold ${fulfillmentType === type ? 'text-accent-primary' : 'text-text-secondary'}`}>
                      {type === 'delivery' ? 'Envío a domicilio' : 'Retiro en tienda'}
                    </span>
                  </button>
                ))}
              </div>

              {/* Shipping options */}
              {fulfillmentType === 'delivery' && (
                <div className="flex flex-col gap-2">
                  {shippingOptions === null ? (
                    <p className="text-sm text-text-muted py-2 text-center">Cargando opciones de envío…</p>
                  ) : deliveryOptions.length === 0 ? (
                    <p className="text-sm text-text-muted py-2 text-center">No hay opciones de envío disponibles.</p>
                  ) : (
                    deliveryOptions.map((option) => (
                      <button
                        key={option.id}
                        onClick={() => setSelectedShippingId(option.id)}
                        className={`flex items-center justify-between px-4 py-3 rounded-xl border-2 transition-colors ${
                          selectedShippingId === option.id
                            ? 'border-accent-primary bg-(--accent-primary)/5'
                            : 'border-border hover:border-border-accent'
                        }`}
                      >
                        <span className="text-sm font-medium text-text-primary">{option.name}</span>
                        <span className="text-sm font-bold text-accent-primary">
                          {option.amount ? formatPrice(option.amount, currencyCode) : 'Gratis'}
                        </span>
                      </button>
                    ))
                  )}
                </div>
              )}

              {/* Pickup info */}
              {fulfillmentType === 'pickup' && (
                <div className="flex items-start gap-3 p-3 rounded-xl bg-bg-elevated">
                  <MapPin className="w-4 h-4 text-text-muted shrink-0 mt-0.5" />
                  <div className="flex flex-col gap-0.5">
                    <p className="text-sm font-semibold text-text-primary">Kādo Gallery</p>
                    {/* TODO: Replace with real store address */}
                    <p className="text-xs text-text-muted">Dirección de la tienda — pendiente</p>
                    <p className="text-xs text-text-muted">Lun–Vie 10:00–19:00 · Sáb 10:00–17:00</p>
                  </div>
                </div>
              )}
            </div>

            {/* Address selector (delivery only) */}
            {fulfillmentType === 'delivery' && (
              <div className="bg-bg-surface rounded-2xl border border-border p-5 flex flex-col gap-3">
                <h2 className="font-heading text-base font-bold text-text-primary">Dirección de entrega</h2>
                {addresses.length === 0 ? (
                  <p className="text-sm text-text-muted py-1">
                    No tienes direcciones guardadas.{' '}
                    <a href="/account" className="text-accent-primary font-semibold hover:underline">
                      Agregar en Mi Cuenta →
                    </a>
                  </p>
                ) : (
                  addresses.map((addr) => {
                    const isSelected = selectedAddress?.id === addr.id
                    const name = [addr.first_name, addr.last_name].filter(Boolean).join(' ')
                    const line = [addr.address_1, addr.city].filter(Boolean).join(', ')
                    return (
                      <button
                        key={addr.id}
                        onClick={() => setSelectedAddress(addr)}
                        className={`flex items-start gap-3 p-3 rounded-xl border-2 text-left transition-colors ${
                          isSelected
                            ? 'border-accent-primary bg-(--accent-primary)/5'
                            : 'border-border hover:border-border-accent'
                        }`}
                      >
                        <MapPin className={`w-4 h-4 shrink-0 mt-0.5 ${isSelected ? 'text-accent-primary' : 'text-text-muted'}`} />
                        <div className="flex-1 flex flex-col gap-0.5">
                          {name && <span className="text-sm font-semibold text-text-primary">{name}</span>}
                          <span className="text-xs text-text-muted">{line}</span>
                        </div>
                        {isSelected && <CheckCircle2 className="w-4 h-4 text-accent-primary shrink-0 mt-0.5" />}
                      </button>
                    )
                  })
                )}
              </div>
            )}
            {/* Billing address */}
            <div className="bg-bg-surface rounded-2xl border border-border p-5 flex flex-col gap-4">
              <h2 className="font-heading text-base font-bold text-text-primary">Dirección de facturación</h2>
              <div className="grid grid-cols-2 gap-3">
                {([
                  { key: 'first_name', label: 'Nombre', placeholder: 'Juan' },
                  { key: 'last_name',  label: 'Apellido', placeholder: 'Pérez' },
                ] as const).map(({ key, label, placeholder }) => (
                  <div key={key} className="flex flex-col gap-1.5">
                    <label className="text-xs font-medium text-text-secondary">{label}</label>
                    <input
                      type="text"
                      placeholder={placeholder}
                      value={billing[key]}
                      onChange={(e) => setBilling((b) => ({ ...b, [key]: e.target.value }))}
                      className="h-10 rounded-xl border border-border bg-bg-elevated px-3 text-sm text-text-primary placeholder:text-text-muted outline-none focus:border-accent-primary transition-colors"
                    />
                  </div>
                ))}
              </div>
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-medium text-text-secondary">Dirección</label>
                <input
                  type="text"
                  placeholder="Av. República E3-71 y Diego de Almagro"
                  value={billing.address_1}
                  onChange={(e) => setBilling((b) => ({ ...b, address_1: e.target.value }))}
                  className="h-10 rounded-xl border border-border bg-bg-elevated px-3 text-sm text-text-primary placeholder:text-text-muted outline-none focus:border-accent-primary transition-colors"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                {([
                  { key: 'city',        label: 'Ciudad',         placeholder: 'Quito' },
                  { key: 'province',    label: 'Provincia',      placeholder: 'Pichincha' },
                  { key: 'postal_code', label: 'Código postal',  placeholder: '170150' },
                  { key: 'phone',       label: 'Teléfono',       placeholder: '+593 99 000 0000' },
                ] as const).map(({ key, label, placeholder }) => (
                  <div key={key} className="flex flex-col gap-1.5">
                    <label className="text-xs font-medium text-text-secondary">{label}</label>
                    <input
                      type="text"
                      placeholder={placeholder}
                      value={billing[key]}
                      onChange={(e) => setBilling((b) => ({ ...b, [key]: e.target.value }))}
                      className="h-10 rounded-xl border border-border bg-bg-elevated px-3 text-sm text-text-primary placeholder:text-text-muted outline-none focus:border-accent-primary transition-colors"
                    />
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* ── Right column ──────────────────────────────────── */}
          <div className="flex flex-col gap-4 lg:sticky lg:top-24 h-fit">

            {/* Price summary */}
            <div className="bg-bg-surface rounded-2xl border border-border p-5 flex flex-col gap-3">
              <h2 className="font-heading text-base font-bold text-text-primary">Resumen</h2>

              <div className="flex justify-between text-sm">
                <span className="text-text-secondary">
                  Subtotal ({items.length} {items.length === 1 ? 'producto' : 'productos'})
                </span>
                <span className="font-medium text-text-primary">{formatPrice(subtotal, currencyCode)}</span>
              </div>

              <div className="flex justify-between text-sm">
                <span className="text-text-secondary">Envío</span>
                {fulfillmentType === 'pickup' ? (
                  <span className="font-medium text-success">Retiro en tienda</span>
                ) : shippingCost > 0 ? (
                  <span className="font-medium text-text-primary">{formatPrice(shippingCost, currencyCode)}</span>
                ) : (
                  <span className="text-text-muted">—</span>
                )}
              </div>

              <Divider />

              <div className="flex items-center justify-between">
                <span className="font-bold text-text-primary">Total</span>
                <span className="font-heading text-2xl font-bold text-accent-primary">
                  {formatPrice(total, currencyCode)}
                </span>
              </div>
            </div>

            {/* Payment method selector */}
            <div className="bg-bg-surface rounded-2xl border border-border p-5 flex flex-col gap-3">
              <h2 className="font-heading text-base font-bold text-text-primary">Método de pago</h2>
              <div className="flex flex-col gap-2">
                {([
                  { id: 'deuna' as const, label: 'DeUna', src: '/Deuna!_icono.png' },
                  { id: 'transfer' as const, label: 'Transferencia bancaria', src: '/banco.png' },
                  { id: 'card' as const, label: 'Tarjeta de débito / crédito', src: '/tarjeta-de-debito.png' },
                ] satisfies { id: NonNullable<PaymentMethod>; label: string; src: string }[]).map(({ id, label, src }) => (
                  <button
                    key={id}
                    onClick={() => setPaymentMethod(id)}
                    className="flex items-center gap-3 px-3 py-3 rounded-xl border border-border hover:border-accent-primary hover:bg-(--accent-primary)/5 transition-colors group cursor-pointer"
                  >
                    <div className="relative w-8 h-8 shrink-0">
                      <Image src={src} alt={label} fill className="object-contain" sizes="32px" />
                    </div>
                    <span className="flex-1 text-sm font-medium text-text-primary text-left">{label}</span>
                    <ChevronRight className="w-4 h-4 text-text-muted group-hover:text-accent-primary transition-colors" />
                  </button>
                ))}
              </div>
            </div>

          </div>
        </div>
      </div>

      <PaymentModal
        method={paymentMethod}
        onClose={() => setPaymentMethod(null)}
        onTransferConfirm={handleTransferConfirm}
        isLoading={isSubmitting}
        error={submitError}
        currencyCode={currencyCode}
      />
    </>
  )
}
